### ISSUE TITLE
Intermittent serialization error when compiling JS

### ISSUE THREAD

**Issue by fuzzyweapon** [polyforest/acornui-gradle-plugin#34]
> If I hit build again it goes away
> -@nbilyk

```stack trace
Task :acornui-core:compileKotlinJs FAILED
e: java.lang.IllegalStateException: Cannot serialize error type: [ERROR : Unknown type parameter 0]
    at org.jetbrains.kotlin.serialization.SerializerExtension.serializeErrorType(SerializerExtension.kt:83)
    at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:536)
    at org.jetbrains.kotlin.serialization.DescriptorSerializer.typeArgument(DescriptorSerializer.kt:639)
    at org.jetbrains.kotlin.serialization.DescriptorSerializer.fillFromPossiblyInnerType(DescriptorSerializer.kt:607)
```

**Comment by fuzzyweapon** [comment]
Not been seen in weeks since clearing caches after JB fix.  Closing.  Please re-open if seen again.
